version: '2'

services:
  flask:
    image: kapb14/python3-flask
    build: .
    container_name: python3-flask
    volumes:
    - ./opt:/opt
    ports:
    - 55000:55000
    restart: unless-stopped

